// Reborn Assistant - Multi-Language System (13 languages)
const translations = {
    fr: {
        // Header
        headerDocs: "📚 Documentation",
        headerBadge: "Premium Edition",
        
        // Hero
        heroTitle: "REBORN<br>ASSISTANT",
        heroSubtitle: "Premium Automation",
        heroDesc: "Bot MMORPG conçu par un joueur. Automatise soins, mana, buffs et familier pour tes classes de support. Parfait pour gérer Prêtre, Clerc, Ringmaster, Bard en multi-fenêtre.",
        heroCta1: "Commencer maintenant",
        heroCta2: "En savoir plus",
        heroTrust1: "Version gratuite à vie",
        heroTrust2: "🎁 7 jours Premium offerts",
        heroTrust3: "Paiement sécurisé Stripe",
        heroTrust4: "Résiliation à tout moment",
        
        // Bannière 7 jours
        banner7Title: "7 JOURS PREMIUM GRATUIT",
        banner7Desc: "Teste toutes les fonctionnalités Premium pendant 7 jours.",
        banner7Price: "Après l'essai : À partir de 2,99€/mois · Résiliation à tout moment",
        banner7Features: "Macro PV · Macro Mana · Buffs auto · Familier · 3 macros perso · CTRL+A/O",
        
        // Features
        featuresTag: "Fonctionnalités",
        featuresTitle: "Tout ce qu'il te <em>faut</em>",
        featuresSubtitle: "Voilà ce que Reborn peut faire pour toi.",
        feature1Title: "Automatisation complète",
        feature1Desc: "PV, Mana, Buffs et Familier gérés automatiquement. Tu joues, Reborn gère le reste.",
        feature2Title: "Données locales",
        feature2Desc: "Tout reste sur ton PC. Zéro tracking, zéro collecte, zéro revente.",
        feature3Title: "3 macros perso",
        feature3Desc: "Configure tes combos. CTRL+A pour lancer, CTRL+O pour stop.",
        feature4Title: "6 thèmes au choix",
        feature4Desc: "Reborn, Neon, Obsidian, Cyber, Matrix, Sakura. Change quand tu veux.",
        feature5Title: "13 langues",
        feature5Desc: "Français, English, Español, Deutsch, Italiano, Português, 日本語, 한국어, 中文, Русский, Polski, Nederlands, Tagalog.",
        feature6Title: "Version gratuite",
        feature6Desc: "Macro soin alliés incluse. Teste avant de passer Premium.",
        
        // Pricing
        pricingTag: "Tarifs",
        pricingTitle: "Choisis ta <em>version</em>",
        pricingSubtitle: "Gratuit pour tester. Premium pour tout débloquer.",
        
        // Plan Free
        planFree: "Gratuit",
        priceFree: "0€",
        periodFree: "à jamais",
        featureFree1: "Macro soin (soigner alliés)",
        featureFree2: "6 thèmes visuels",
        featureFree3: "13 langues disponibles",
        featureFree4: "Interface flottante",
        btnFree: "Télécharger gratuit",
        guaranteeFree: "🔒 Gratuit à vie · Aucune limite de temps",
        downloadApp: "⬇ Télécharger l'application",
        
        // Plan Monthly
        planMonthly: "Mensuel",
        priceMonthly: "2,99€",
        periodMonthly: "par mois",
        featurePremium1: "Macro PV automatique",
        featurePremium2: "Macro Mana automatique",
        featurePremium3: "Buffs automatiques",
        featurePremium4: "Familier automatique",
        featurePremium5: "3 macros configurables",
        featurePremium6: "Raccourcis CTRL+A / CTRL+O",
        featurePremium7: "Support prioritaire",
        btnMonthly: "Essayer 7 jours gratuit",
        guaranteeMonthly: "🎁 7 jours offerts · Puis 2,99€/mois · Résiliation à tout moment",
        
        // Plan Yearly
        badgeYearly: "⭐ Populaire",
        planYearly: "Annuel",
        priceYearly: "29,99€",
        periodYearly: "par an · soit 2,50€/mois",
        featureYearly8: "Économie de 17% vs mensuel",
        btnYearly: "Essayer 7 jours gratuit",
        guaranteeYearly: "🎁 7 jours offerts · Puis 29,99€/an",
        
        // Plan Lifetime
        badgeLifetime: "⚡ Offre Limitée",
        planLifetime: "À Vie",
        priceLifetime: "99,99€",
        periodLifetime: "paiement unique · plus jamais rien",
        featureLifetime1: "Accès à vie",
        featureLifetime2: "Toutes les mises à jour futures",
        featureLifetime3: "Support premium dédié",
        featureLifetime4: "Meilleur rapport qualité-prix",
        btnLifetime: "Acheter à vie",
        guaranteeLifetime: "🔒 Paiement unique · Accès à vie garanti",
        
        // Stats
        stat1: "13",
        statLabel1: "Langues disponibles",
        stat2: "6",
        statLabel2: "Thèmes visuels",
        stat3: "100%",
        statLabel3: "Données locales",
        stat4: "24/7",
        statLabel4: "Toujours actif",
        
        // FAQ
        faqTag: "FAQ",
        faqTitle: "Questions <em>fréquentes</em>",
        faqSubtitle: "Les réponses aux questions qu'on me pose souvent.",
        
        faq1Q: "L'essai gratuit nécessite-t-il une carte bancaire ?",
        faq1A: "Oui, une carte est requise pour l'essai, mais tu ne seras pas débité pendant les 7 premiers jours. Tu peux annuler à tout moment avant la fin de la période d'essai.",
        
        faq2Q: "Puis-je changer de plan à tout moment ?",
        faq2A: "Oui, tu peux passer à un plan supérieur ou inférieur à tout moment depuis ton espace client. Aucun frais de changement.",
        
        faq3Q: "Le plan À Vie inclut-il vraiment toutes les futures mises à jour ?",
        faq3A: "Absolument. Le plan À Vie te garantit l'accès à toutes les mises à jour et nouvelles fonctionnalités futures, sans jamais débourser quoi que ce soit de plus.",
        
        faq4Q: "Mes données sont-elles en sécurité ?",
        faq4A: "Toutes tes données restent stockées localement sur ton appareil. Nous ne collectons aucune donnée personnelle et n'utilisons aucun tracking ou télémétrie.",
        
        faq5Q: "Comment contacter le support ?",
        faq5A: "Contacte-nous directement par email à seymoon.cell@gmail.com. Les abonnés premium bénéficient d'une réponse prioritaire.",
        
        // Roadmap
        roadmapTitle: "À venir",
        roadmapSoon: "BIENTÔT (Mars 2026)",
        roadmapSoonTitle: "Publication sur le Chrome Web Store",
        roadmapSoon1: "Téléchargement officiel Google",
        roadmapSoon2: "Installation en 1 clic",
        roadmapSoon3: "Mises à jour automatiques",
        roadmapSoon4: "Plus besoin de Mediafire",
        
        roadmapDev: "EN PRÉPARATION (T2 2026)",
        roadmapDevTitle: "Application de Bureau",
        roadmapDev1: "Windows, macOS, Linux",
        roadmapDev2: "Fonctionne avec TOUS les jeux",
        roadmapDev3: "Support jeux clients (non-navigateur)",
        roadmapDev4: "Interface standalone",
        
        roadmapNewsletter: "📧 Restez informé des nouveautés",
        roadmapNewsletterDesc: "Inscrivez-vous à la newsletter pour recevoir les annonces de lancement",
        
        // Footer
        footerDocs: "Documentation",
        footerPrivacy: "Confidentialité",
        footerLegal: "Conditions d'Utilisation",
        footerSupport: "Support",
        footerContact: "Contact",
        footerCopyright: "© 2026 Reborn Assistant. Tous droits réservés.<br>Développé par Seymoon"
    },
    
    en: {
        // Header
        headerDocs: "📚 Documentation",
        headerBadge: "Premium Edition",
        
        // Hero
        heroTitle: "REBORN<br>ASSISTANT",
        heroSubtitle: "Premium Automation",
        heroDesc: "MMORPG bot designed by a player. Automates heals, mana, buffs and pet for your support classes. Perfect for managing Priest, Cleric, Ringmaster, Bard in multi-window.",
        heroCta1: "Get Started",
        heroCta2: "Learn More",
        heroTrust1: "Free version forever",
        heroTrust2: "🎁 7 days Premium free",
        heroTrust3: "Secure payment via Stripe",
        heroTrust4: "Cancel anytime",
        
        // Bannière 7 jours
        banner7Title: "7 DAYS PREMIUM FREE",
        banner7Desc: "Test all Premium features for 7 days.",
        banner7Price: "After trial: From €2.99/month · Cancel anytime",
        banner7Features: "HP Macro · Mana Macro · Auto Buffs · Pet · 3 custom macros · CTRL+A/O",
        
        // Features
        featuresTag: "Features",
        featuresTitle: "Everything you <em>need</em>",
        featuresSubtitle: "Here's what Reborn can do for you.",
        feature1Title: "Complete Automation",
        feature1Desc: "HP, Mana, Buffs and Pet managed automatically. You play, Reborn handles the rest.",
        feature2Title: "Local Data",
        feature2Desc: "Everything stays on your PC. Zero tracking, zero collection, zero reselling.",
        feature3Title: "3 custom macros",
        feature3Desc: "Configure your combos. CTRL+A to start, CTRL+O to stop.",
        feature4Title: "6 themes",
        feature4Desc: "Reborn, Neon, Obsidian, Cyber, Matrix, Sakura. Change whenever you want.",
        feature5Title: "13 languages",
        feature5Desc: "Français, English, Español, Deutsch, Italiano, Português, 日本語, 한국어, 中文, Русский, Polski, Nederlands, Tagalog.",
        feature6Title: "Free version",
        feature6Desc: "Heal allies macro included. Test before going Premium.",
        
        // Pricing
        pricingTag: "Pricing",
        pricingTitle: "Choose your <em>plan</em>",
        pricingSubtitle: "Free to test. Premium to unlock everything.",
        
        // Plan Free
        planFree: "Free",
        priceFree: "€0",
        periodFree: "forever",
        featureFree1: "Heal macro (heal allies)",
        featureFree2: "6 visual themes",
        featureFree3: "13 languages available",
        featureFree4: "Floating interface",
        btnFree: "Download free",
        guaranteeFree: "🔒 Free forever · No time limit",
        downloadApp: "⬇ Download application",
        
        // Plan Monthly
        planMonthly: "Monthly",
        priceMonthly: "€2.99",
        periodMonthly: "per month",
        featurePremium1: "Auto HP macro",
        featurePremium2: "Auto Mana macro",
        featurePremium3: "Auto buffs",
        featurePremium4: "Auto pet",
        featurePremium5: "3 configurable macros",
        featurePremium6: "CTRL+A / CTRL+O shortcuts",
        featurePremium7: "Priority support",
        btnMonthly: "Try 7 days free",
        guaranteeMonthly: "🎁 7 days free · Then €2.99/month · Cancel anytime",
        
        // Plan Yearly
        badgeYearly: "⭐ Popular",
        planYearly: "Yearly",
        priceYearly: "€29.99",
        periodYearly: "per year · €2.50/month",
        featureYearly8: "Save 17% vs monthly",
        btnYearly: "Try 7 days free",
        guaranteeYearly: "🎁 7 days free · Then €29.99/year",
        
        // Plan Lifetime
        badgeLifetime: "⚡ Limited Offer",
        planLifetime: "Lifetime",
        priceLifetime: "€99.99",
        periodLifetime: "one-time payment · never pay again",
        featureLifetime1: "Lifetime access",
        featureLifetime2: "All future updates",
        featureLifetime3: "Dedicated premium support",
        featureLifetime4: "Best value",
        btnLifetime: "Buy lifetime",
        guaranteeLifetime: "🔒 One-time payment · Lifetime access guaranteed",
        
        // Stats
        stat1: "13",
        statLabel1: "Languages available",
        stat2: "6",
        statLabel2: "Visual themes",
        stat3: "100%",
        statLabel3: "Local data",
        stat4: "24/7",
        statLabel4: "Always active",
        
        // FAQ
        faqTag: "FAQ",
        faqTitle: "Frequently <em>asked questions</em>",
        faqSubtitle: "Answers to common questions.",
        
        faq1Q: "Does the free trial require a credit card?",
        faq1A: "Yes, a card is required for the trial, but you won't be charged during the first 7 days. You can cancel anytime before the trial ends.",
        
        faq2Q: "Can I change plans anytime?",
        faq2A: "Yes, you can upgrade or downgrade anytime from your customer portal. No change fees.",
        
        faq3Q: "Does the Lifetime plan really include all future updates?",
        faq3A: "Absolutely. The Lifetime plan guarantees access to all updates and new features forever, without ever paying anything more.",
        
        faq4Q: "Is my data secure?",
        faq4A: "All your data stays stored locally on your device. We don't collect any personal data and use no tracking or telemetry.",
        
        faq5Q: "How do I contact support?",
        faq5A: "Contact us directly by email at seymoon.cell@gmail.com. Premium subscribers get priority response.",
        
        // Roadmap
        roadmapTitle: "Coming Soon",
        roadmapSoon: "SOON (March 2026)",
        roadmapSoonTitle: "Chrome Web Store Release",
        roadmapSoon1: "Official Google download",
        roadmapSoon2: "1-click install",
        roadmapSoon3: "Automatic updates",
        roadmapSoon4: "No more Mediafire",
        
        roadmapDev: "IN DEVELOPMENT (Q2 2026)",
        roadmapDevTitle: "Desktop Application",
        roadmapDev1: "Windows, macOS, Linux",
        roadmapDev2: "Works with ALL games",
        roadmapDev3: "Client games support (non-browser)",
        roadmapDev4: "Standalone interface",
        
        roadmapNewsletter: "📧 Stay informed",
        roadmapNewsletterDesc: "Subscribe to the newsletter for launch announcements",
        
        // Footer
        footerDocs: "Documentation",
        footerPrivacy: "Privacy",
        footerLegal: "Terms of Use",
        footerSupport: "Support",
        footerContact: "Contact",
        footerCopyright: "© 2026 Reborn Assistant. All rights reserved.<br>Developed by Seymoon"
    },
    
    es: {
        // Header
        headerDocs: "📚 Documentación",
        headerBadge: "Edición Premium",
        
        // Hero
        heroTitle: "REBORN<br>ASSISTANT",
        heroSubtitle: "Automatización Premium",
        heroDesc: "Bot MMORPG diseñado por un jugador. Automatiza curaciones, maná, buffs y mascota para tus clases de soporte. Perfecto para gestionar Sacerdote, Clérigo, Ringmaster, Bardo en multi-ventana.",
        heroCta1: "Empezar ahora",
        heroCta2: "Saber más",
        heroTrust1: "Versión gratuita para siempre",
        heroTrust2: "🎁 7 días Premium gratis",
        heroTrust3: "Pago seguro vía Stripe",
        heroTrust4: "Cancelar cuando quieras",
        
        // Bannière 7 jours
        banner7Title: "7 DÍAS PREMIUM GRATIS",
        banner7Desc: "Prueba todas las funciones Premium durante 7 días.",
        banner7Price: "Después: Desde 2,99€/mes · Cancelar cuando quieras",
        banner7Features: "Macro PV · Macro Maná · Buffs auto · Mascota · 3 macros personalizados · CTRL+A/O",
        
        // Features
        featuresTag: "Funciones",
        featuresTitle: "Todo lo que <em>necesitas</em>",
        featuresSubtitle: "Esto es lo que Reborn puede hacer por ti.",
        feature1Title: "Automatización completa",
        feature1Desc: "PV, Maná, Buffs y Mascota gestionados automáticamente. Tú juegas, Reborn se encarga del resto.",
        feature2Title: "Datos locales",
        feature2Desc: "Todo permanece en tu PC. Cero rastreo, cero recopilación, cero reventa.",
        feature3Title: "3 macros personalizados",
        feature3Desc: "Configura tus combos. CTRL+A para iniciar, CTRL+O para detener.",
        feature4Title: "6 temas",
        feature4Desc: "Reborn, Neon, Obsidian, Cyber, Matrix, Sakura. Cambia cuando quieras.",
        feature5Title: "13 idiomas",
        feature5Desc: "Français, English, Español, Deutsch, Italiano, Português, 日本語, 한국어, 中文, Русский, Polski, Nederlands, Tagalog.",
        feature6Title: "Versión gratuita",
        feature6Desc: "Macro de curación de aliados incluida. Prueba antes de pasarte a Premium.",
        
        // Pricing
        pricingTag: "Precios",
        pricingTitle: "Elige tu <em>plan</em>",
        pricingSubtitle: "Gratis para probar. Premium para desbloquearlo todo.",
        
        // Plan Free
        planFree: "Gratis",
        priceFree: "0€",
        periodFree: "para siempre",
        featureFree1: "Macro curación (curar aliados)",
        featureFree2: "6 temas visuales",
        featureFree3: "13 idiomas disponibles",
        featureFree4: "Interfaz flotante",
        btnFree: "Descargar gratis",
        guaranteeFree: "🔒 Gratis para siempre · Sin límite de tiempo",
        downloadApp: "⬇ Descargar aplicación",
        
        // Plan Monthly
        planMonthly: "Mensual",
        priceMonthly: "2,99€",
        periodMonthly: "por mes",
        featurePremium1: "Macro PV automático",
        featurePremium2: "Macro Maná automático",
        featurePremium3: "Buffs automáticos",
        featurePremium4: "Mascota automática",
        featurePremium5: "3 macros configurables",
        featurePremium6: "Atajos CTRL+A / CTRL+O",
        featurePremium7: "Soporte prioritario",
        btnMonthly: "Probar 7 días gratis",
        guaranteeMonthly: "🎁 7 días gratis · Luego 2,99€/mes · Cancelar cuando quieras",
        
        // Plan Yearly
        badgeYearly: "⭐ Popular",
        planYearly: "Anual",
        priceYearly: "29,99€",
        periodYearly: "por año · 2,50€/mes",
        featureYearly8: "Ahorra 17% vs mensual",
        btnYearly: "Probar 7 días gratis",
        guaranteeYearly: "🎁 7 días gratis · Luego 29,99€/año",
        
        // Plan Lifetime
        badgeLifetime: "⚡ Oferta Limitada",
        planLifetime: "De por Vida",
        priceLifetime: "99,99€",
        periodLifetime: "pago único · nunca más",
        featureLifetime1: "Acceso de por vida",
        featureLifetime2: "Todas las actualizaciones futuras",
        featureLifetime3: "Soporte premium dedicado",
        featureLifetime4: "Mejor relación calidad-precio",
        btnLifetime: "Comprar de por vida",
        guaranteeLifetime: "🔒 Pago único · Acceso de por vida garantizado",
        
        // Stats
        stat1: "13",
        statLabel1: "Idiomas disponibles",
        stat2: "6",
        statLabel2: "Temas visuales",
        stat3: "100%",
        statLabel3: "Datos locales",
        stat4: "24/7",
        statLabel4: "Siempre activo",
        
        // FAQ
        faqTag: "FAQ",
        faqTitle: "Preguntas <em>frecuentes</em>",
        faqSubtitle: "Respuestas a preguntas comunes.",
        
        faq1Q: "¿La prueba gratuita requiere tarjeta de crédito?",
        faq1A: "Sí, se requiere una tarjeta para la prueba, pero no se te cobrará durante los primeros 7 días. Puedes cancelar en cualquier momento antes de que termine la prueba.",
        
        faq2Q: "¿Puedo cambiar de plan en cualquier momento?",
        faq2A: "Sí, puedes actualizar o degradar en cualquier momento desde tu portal de cliente. Sin comisiones de cambio.",
        
        faq3Q: "¿El plan De por Vida realmente incluye todas las actualizaciones futuras?",
        faq3A: "Absolutamente. El plan De por Vida garantiza acceso a todas las actualizaciones y nuevas funciones para siempre, sin pagar nunca nada más.",
        
        faq4Q: "¿Están seguros mis datos?",
        faq4A: "Todos tus datos permanecen almacenados localmente en tu dispositivo. No recopilamos datos personales ni usamos rastreo o telemetría.",
        
        faq5Q: "¿Cómo contacto con el soporte?",
        faq5A: "Contáctanos directamente por email en seymoon.cell@gmail.com. Los suscriptores premium obtienen respuesta prioritaria.",
        
        // Roadmap
        roadmapTitle: "Próximamente",
        roadmapSoon: "PRONTO (Marzo 2026)",
        roadmapSoonTitle: "Lanzamiento en Chrome Web Store",
        roadmapSoon1: "Descarga oficial de Google",
        roadmapSoon2: "Instalación en 1 clic",
        roadmapSoon3: "Actualizaciones automáticas",
        roadmapSoon4: "No más Mediafire",
        
        roadmapDev: "EN DESARROLLO (T2 2026)",
        roadmapDevTitle: "Aplicación de Escritorio",
        roadmapDev1: "Windows, macOS, Linux",
        roadmapDev2: "Funciona con TODOS los juegos",
        roadmapDev3: "Soporte de juegos cliente (no navegador)",
        roadmapDev4: "Interfaz independiente",
        
        roadmapNewsletter: "📧 Mantente informado",
        roadmapNewsletterDesc: "Suscríbete al boletín para anuncios de lanzamiento",
        
        // Footer
        footerDocs: "Documentación",
        footerPrivacy: "Privacidad",
        footerLegal: "Términos de Uso",
        footerSupport: "Soporte",
        footerContact: "Contacto",
        footerCopyright: "© 2026 Reborn Assistant. Todos los derechos reservados.<br>Desarrollado por Seymoon"
    },
    
    de: {
        headerDocs: "📚 Dokumentation",
        headerBadge: "Premium Edition",
        heroTitle: "REBORN<br>ASSISTANT",
        heroSubtitle: "Premium Automatisierung",
        heroDesc: "MMORPG-Bot von einem Spieler entwickelt. Automatisiert Heilung, Mana, Buffs und Haustier für deine Support-Klassen. Perfekt für Priester, Kleriker, Ringmaster, Barde im Multi-Fenster.",
        heroCta1: "Jetzt starten",
        heroCta2: "Mehr erfahren",
        heroTrust1: "Kostenlose Version für immer",
        heroTrust2: "🎁 7 Tage Premium gratis",
        heroTrust3: "Sichere Zahlung via Stripe",
        heroTrust4: "Jederzeit kündbar",
        banner7Title: "7 TAGE PREMIUM GRATIS",
        banner7Desc: "Teste alle Premium-Funktionen 7 Tage lang.",
        banner7Price: "Danach: Ab 2,99€/Monat · Jederzeit kündbar",
        banner7Features: "HP Makro · Mana Makro · Auto Buffs · Haustier · 3 eigene Makros · STRG+A/O",
        featuresTag: "Funktionen",
        featuresTitle: "Alles was du <em>brauchst</em>",
        featuresSubtitle: "Das kann Reborn für dich tun.",
        feature1Title: "Vollständige Automatisierung",
        feature1Desc: "HP, Mana, Buffs und Haustier automatisch verwaltet. Du spielst, Reborn kümmert sich um den Rest.",
        feature2Title: "Lokale Daten",
        feature2Desc: "Alles bleibt auf deinem PC. Null Tracking, null Sammlung, null Weiterverkauf.",
        feature3Title: "3 eigene Makros",
        feature3Desc: "Konfiguriere deine Combos. STRG+A zum Starten, STRG+O zum Stoppen.",
        feature4Title: "6 Themes",
        feature4Desc: "Reborn, Neon, Obsidian, Cyber, Matrix, Sakura. Wechsle wann du willst.",
        feature5Title: "13 Sprachen",
        feature5Desc: "Français, English, Español, Deutsch, Italiano, Português, 日本語, 한국어, 中文, Русский, Polski, Nederlands, Tagalog.",
        feature6Title: "Kostenlose Version",
        feature6Desc: "Heilungs-Makro inklusive. Teste vor Premium.",
        pricingTag: "Preise",
        pricingTitle: "Wähle deinen <em>Plan</em>",
        pricingSubtitle: "Kostenlos zum Testen. Premium für alles.",
        planFree: "Kostenlos",
        priceFree: "0€",
        periodFree: "für immer",
        featureFree1: "Heilungs-Makro (Verbündete heilen)",
        featureFree2: "6 visuelle Themes",
        featureFree3: "13 Sprachen verfügbar",
        featureFree4: "Schwebende Oberfläche",
        btnFree: "Kostenlos herunterladen",
        guaranteeFree: "🔒 Für immer kostenlos · Keine Zeitbegrenzung",
        downloadApp: "⬇ Anwendung herunterladen",
        planMonthly: "Monatlich",
        priceMonthly: "2,99€",
        periodMonthly: "pro Monat",
        featurePremium1: "Auto HP Makro",
        featurePremium2: "Auto Mana Makro",
        featurePremium3: "Auto Buffs",
        featurePremium4: "Auto Haustier",
        featurePremium5: "3 konfigurierbare Makros",
        featurePremium6: "STRG+A / STRG+O Shortcuts",
        featurePremium7: "Prioritäts-Support",
        btnMonthly: "7 Tage gratis testen",
        guaranteeMonthly: "🎁 7 Tage gratis · Dann 2,99€/Monat · Jederzeit kündbar",
        badgeYearly: "⭐ Beliebt",
        planYearly: "Jährlich",
        priceYearly: "29,99€",
        periodYearly: "pro Jahr · 2,50€/Monat",
        featureYearly8: "Spare 17% vs monatlich",
        btnYearly: "7 Tage gratis testen",
        guaranteeYearly: "🎁 7 Tage gratis · Dann 29,99€/Jahr",
        badgeLifetime: "⚡ Begrenztes Angebot",
        planLifetime: "Lebenslang",
        priceLifetime: "99,99€",
        periodLifetime: "einmalige Zahlung · nie wieder zahlen",
        featureLifetime1: "Lebenslanger Zugang",
        featureLifetime2: "Alle zukünftigen Updates",
        featureLifetime3: "Dedizierter Premium-Support",
        featureLifetime4: "Bestes Preis-Leistungs-Verhältnis",
        btnLifetime: "Lebenslang kaufen",
        guaranteeLifetime: "🔒 Einmalige Zahlung · Lebenslanger Zugang garantiert",
        stat1: "13",
        statLabel1: "Sprachen verfügbar",
        stat2: "6",
        statLabel2: "Visuelle Themes",
        stat3: "100%",
        statLabel3: "Lokale Daten",
        stat4: "24/7",
        statLabel4: "Immer aktiv",
        faqTag: "FAQ",
        faqTitle: "Häufig gestellte <em>Fragen</em>",
        faqSubtitle: "Antworten auf häufige Fragen.",
        faq1Q: "Benötigt die kostenlose Testversion eine Kreditkarte?",
        faq1A: "Ja, eine Karte wird für den Test benötigt, aber du wirst in den ersten 7 Tagen nicht belastet. Du kannst jederzeit vor Ende des Tests kündigen.",
        faq2Q: "Kann ich den Plan jederzeit wechseln?",
        faq2A: "Ja, du kannst jederzeit über dein Kundenportal upgraden oder downgraden. Keine Wechselgebühren.",
        faq3Q: "Beinhaltet der Lebenslang-Plan wirklich alle zukünftigen Updates?",
        faq3A: "Absolut. Der Lebenslang-Plan garantiert Zugang zu allen Updates und neuen Funktionen für immer, ohne jemals wieder etwas zu zahlen.",
        faq4Q: "Sind meine Daten sicher?",
        faq4A: "Alle deine Daten bleiben lokal auf deinem Gerät gespeichert. Wir sammeln keine persönlichen Daten und verwenden kein Tracking oder Telemetrie.",
        faq5Q: "Wie kontaktiere ich den Support?",
        faq5A: "Kontaktiere uns direkt per E-Mail an seymoon.cell@gmail.com. Premium-Abonnenten erhalten vorrangige Antwort.",
        roadmapTitle: "Demnächst",
        roadmapSoon: "BALD (März 2026)",
        roadmapSoonTitle: "Veröffentlichung im Chrome Web Store",
        roadmapSoon1: "Offizieller Google-Download",
        roadmapSoon2: "1-Klick-Installation",
        roadmapSoon3: "Automatische Updates",
        roadmapSoon4: "Kein Mediafire mehr",
        roadmapDev: "IN ENTWICKLUNG (Q2 2026)",
        roadmapDevTitle: "Desktop-Anwendung",
        roadmapDev1: "Windows, macOS, Linux",
        roadmapDev2: "Funktioniert mit ALLEN Spielen",
        roadmapDev3: "Client-Spiele-Unterstützung (nicht Browser)",
        roadmapDev4: "Eigenständige Oberfläche",
        roadmapNewsletter: "📧 Bleib informiert",
        roadmapNewsletterDesc: "Abonniere den Newsletter für Start-Ankündigungen",
        footerDocs: "Dokumentation",
        footerPrivacy: "Datenschutz",
        footerLegal: "Nutzungsbedingungen",
        footerSupport: "Support",
        footerContact: "Kontakt",
        footerCopyright: "© 2026 Reborn Assistant. Alle Rechte vorbehalten.<br>Entwickelt von Seymoon"
    },
    
    it: {
        headerDocs: "📚 Documentazione",
        headerBadge: "Edizione Premium",
        heroTitle: "REBORN<br>ASSISTANT",
        heroSubtitle: "Automazione Premium",
        heroDesc: "Bot MMORPG progettato da un giocatore. Automatizza cure, mana, buff e famiglio per le tue classi di supporto. Perfetto per gestire Prete, Chierico, Ringmaster, Bardo in multi-finestra.",
        heroCta1: "Inizia ora",
        heroCta2: "Scopri di più",
        heroTrust1: "Versione gratuita per sempre",
        heroTrust2: "🎁 7 giorni Premium gratis",
        heroTrust3: "Pagamento sicuro via Stripe",
        heroTrust4: "Annulla quando vuoi",
        banner7Title: "7 GIORNI PREMIUM GRATIS",
        banner7Desc: "Prova tutte le funzioni Premium per 7 giorni.",
        banner7Price: "Dopo: Da 2,99€/mese · Annulla quando vuoi",
        banner7Features: "Macro PV · Macro Mana · Buff auto · Famiglio · 3 macro personalizzati · CTRL+A/O",
        featuresTag: "Funzionalità",
        featuresTitle: "Tutto ciò di cui <em>hai bisogno</em>",
        featuresSubtitle: "Ecco cosa Reborn può fare per te.",
        feature1Title: "Automazione completa",
        feature1Desc: "PV, Mana, Buff e Famiglio gestiti automaticamente. Tu giochi, Reborn si occupa del resto.",
        feature2Title: "Dati locali",
        feature2Desc: "Tutto rimane sul tuo PC. Zero tracciamento, zero raccolta, zero rivendita.",
        feature3Title: "3 macro personalizzati",
        feature3Desc: "Configura le tue combo. CTRL+A per avviare, CTRL+O per fermare.",
        feature4Title: "6 temi",
        feature4Desc: "Reborn, Neon, Obsidian, Cyber, Matrix, Sakura. Cambia quando vuoi.",
        feature5Title: "13 lingue",
        feature5Desc: "Français, English, Español, Deutsch, Italiano, Português, 日本語, 한국어, 中文, Русский, Polski, Nederlands, Tagalog.",
        feature6Title: "Versione gratuita",
        feature6Desc: "Macro cura alleati inclusa. Prova prima di passare a Premium.",
        pricingTag: "Prezzi",
        pricingTitle: "Scegli il tuo <em>piano</em>",
        pricingSubtitle: "Gratis per provare. Premium per sbloccare tutto.",
        planFree: "Gratuito",
        priceFree: "0€",
        periodFree: "per sempre",
        featureFree1: "Macro cura (curare alleati)",
        featureFree2: "6 temi visivi",
        featureFree3: "13 lingue disponibili",
        featureFree4: "Interfaccia fluttuante",
        btnFree: "Scarica gratis",
        guaranteeFree: "🔒 Gratis per sempre · Nessun limite di tempo",
        downloadApp: "⬇ Scarica applicazione",
        planMonthly: "Mensile",
        priceMonthly: "2,99€",
        periodMonthly: "al mese",
        featurePremium1: "Macro PV automatico",
        featurePremium2: "Macro Mana automatico",
        featurePremium3: "Buff automatici",
        featurePremium4: "Famiglio automatico",
        featurePremium5: "3 macro configurabili",
        featurePremium6: "Scorciatoie CTRL+A / CTRL+O",
        featurePremium7: "Supporto prioritario",
        btnMonthly: "Prova 7 giorni gratis",
        guaranteeMonthly: "🎁 7 giorni gratis · Poi 2,99€/mese · Annulla quando vuoi",
        badgeYearly: "⭐ Popolare",
        planYearly: "Annuale",
        priceYearly: "29,99€",
        periodYearly: "all'anno · 2,50€/mese",
        featureYearly8: "Risparmia 17% vs mensile",
        btnYearly: "Prova 7 giorni gratis",
        guaranteeYearly: "🎁 7 giorni gratis · Poi 29,99€/anno",
        badgeLifetime: "⚡ Offerta Limitata",
        planLifetime: "A Vita",
        priceLifetime: "99,99€",
        periodLifetime: "pagamento unico · mai più",
        featureLifetime1: "Accesso a vita",
        featureLifetime2: "Tutti gli aggiornamenti futuri",
        featureLifetime3: "Supporto premium dedicato",
        featureLifetime4: "Miglior rapporto qualità-prezzo",
        btnLifetime: "Acquista a vita",
        guaranteeLifetime: "🔒 Pagamento unico · Accesso a vita garantito",
        stat1: "13",
        statLabel1: "Lingue disponibili",
        stat2: "6",
        statLabel2: "Temi visivi",
        stat3: "100%",
        statLabel3: "Dati locali",
        stat4: "24/7",
        statLabel4: "Sempre attivo",
        faqTag: "FAQ",
        faqTitle: "Domande <em>frequenti</em>",
        faqSubtitle: "Risposte alle domande comuni.",
        faq1Q: "La prova gratuita richiede una carta di credito?",
        faq1A: "Sì, è richiesta una carta per la prova, ma non ti verrà addebitato nulla durante i primi 7 giorni. Puoi annullare in qualsiasi momento prima della fine della prova.",
        faq2Q: "Posso cambiare piano in qualsiasi momento?",
        faq2A: "Sì, puoi fare upgrade o downgrade in qualsiasi momento dal tuo portale cliente. Nessuna commissione di cambio.",
        faq3Q: "Il piano A Vita include davvero tutti gli aggiornamenti futuri?",
        faq3A: "Assolutamente. Il piano A Vita garantisce l'accesso a tutti gli aggiornamenti e le nuove funzionalità per sempre, senza mai pagare nulla di più.",
        faq4Q: "I miei dati sono sicuri?",
        faq4A: "Tutti i tuoi dati rimangono memorizzati localmente sul tuo dispositivo. Non raccogliamo dati personali e non usiamo tracciamento o telemetria.",
        faq5Q: "Come contatto il supporto?",
        faq5A: "Contattaci direttamente via email a seymoon.cell@gmail.com. Gli abbonati premium ricevono risposta prioritaria.",
        roadmapTitle: "Prossimamente",
        roadmapSoon: "PRESTO (Marzo 2026)",
        roadmapSoonTitle: "Rilascio su Chrome Web Store",
        roadmapSoon1: "Download ufficiale Google",
        roadmapSoon2: "Installazione con 1 clic",
        roadmapSoon3: "Aggiornamenti automatici",
        roadmapSoon4: "Niente più Mediafire",
        roadmapDev: "IN SVILUPPO (Q2 2026)",
        roadmapDevTitle: "Applicazione Desktop",
        roadmapDev1: "Windows, macOS, Linux",
        roadmapDev2: "Funziona con TUTTI i giochi",
        roadmapDev3: "Supporto giochi client (non browser)",
        roadmapDev4: "Interfaccia standalone",
        roadmapNewsletter: "📧 Resta informato",
        roadmapNewsletterDesc: "Iscriviti alla newsletter per gli annunci di lancio",
        footerDocs: "Documentazione",
        footerPrivacy: "Privacy",
        footerLegal: "Termini di Utilizzo",
        footerSupport: "Supporto",
        footerContact: "Contatto",
        footerCopyright: "© 2026 Reborn Assistant. Tutti i diritti riservati.<br>Sviluppato da Seymoon"
    },
    
    pt: {
        headerDocs: "📚 Documentação",
        headerBadge: "Edição Premium",
        heroTitle: "REBORN<br>ASSISTANT",
        heroSubtitle: "Automação Premium",
        heroDesc: "Bot MMORPG criado por um jogador. Automatiza curas, mana, buffs e pet para suas classes de suporte. Perfeito para gerenciar Sacerdote, Clérigo, Ringmaster, Bardo em multi-janela.",
        heroCta1: "Começar agora",
        heroCta2: "Saiba mais",
        heroTrust1: "Versão gratuita para sempre",
        heroTrust2: "🎁 7 dias Premium grátis",
        heroTrust3: "Pagamento seguro via Stripe",
        heroTrust4: "Cancele quando quiser",
        banner7Title: "7 DIAS PREMIUM GRÁTIS",
        banner7Desc: "Teste todas as funcionalidades Premium por 7 dias.",
        banner7Price: "Depois: A partir de 2,99€/mês · Cancele quando quiser",
        banner7Features: "Macro PV · Macro Mana · Buffs auto · Pet · 3 macros personalizados · CTRL+A/O",
        featuresTag: "Funcionalidades",
        featuresTitle: "Tudo o que você <em>precisa</em>",
        featuresSubtitle: "Veja o que Reborn pode fazer por você.",
        feature1Title: "Automação completa",
        feature1Desc: "PV, Mana, Buffs e Pet gerenciados automaticamente. Você joga, Reborn cuida do resto.",
        feature2Title: "Dados locais",
        feature2Desc: "Tudo fica no seu PC. Zero rastreamento, zero coleta, zero revenda.",
        feature3Title: "3 macros personalizados",
        feature3Desc: "Configure seus combos. CTRL+A para iniciar, CTRL+O para parar.",
        feature4Title: "6 temas",
        feature4Desc: "Reborn, Neon, Obsidian, Cyber, Matrix, Sakura. Mude quando quiser.",
        feature5Title: "13 idiomas",
        feature5Desc: "Français, English, Español, Deutsch, Italiano, Português, 日本語, 한국어, 中文, Русский, Polski, Nederlands, Tagalog.",
        feature6Title: "Versão gratuita",
        feature6Desc: "Macro de cura de aliados incluída. Teste antes de ir Premium.",
        pricingTag: "Preços",
        pricingTitle: "Escolha seu <em>plano</em>",
        pricingSubtitle: "Grátis para testar. Premium para desbloquear tudo.",
        planFree: "Gratuito",
        priceFree: "0€",
        periodFree: "para sempre",
        featureFree1: "Macro cura (curar aliados)",
        featureFree2: "6 temas visuais",
        featureFree3: "13 idiomas disponíveis",
        featureFree4: "Interface flutuante",
        btnFree: "Baixar grátis",
        guaranteeFree: "🔒 Grátis para sempre · Sem limite de tempo",
        downloadApp: "⬇ Baixar aplicação",
        planMonthly: "Mensal",
        priceMonthly: "2,99€",
        periodMonthly: "por mês",
        featurePremium1: "Macro PV automático",
        featurePremium2: "Macro Mana automático",
        featurePremium3: "Buffs automáticos",
        featurePremium4: "Pet automático",
        featurePremium5: "3 macros configuráveis",
        featurePremium6: "Atalhos CTRL+A / CTRL+O",
        featurePremium7: "Suporte prioritário",
        btnMonthly: "Testar 7 dias grátis",
        guaranteeMonthly: "🎁 7 dias grátis · Depois 2,99€/mês · Cancele quando quiser",
        badgeYearly: "⭐ Popular",
        planYearly: "Anual",
        priceYearly: "29,99€",
        periodYearly: "por ano · 2,50€/mês",
        featureYearly8: "Economize 17% vs mensal",
        btnYearly: "Testar 7 dias grátis",
        guaranteeYearly: "🎁 7 dias grátis · Depois 29,99€/ano",
        badgeLifetime: "⚡ Oferta Limitada",
        planLifetime: "Vitalício",
        priceLifetime: "99,99€",
        periodLifetime: "pagamento único · nunca mais",
        featureLifetime1: "Acesso vitalício",
        featureLifetime2: "Todas as atualizações futuras",
        featureLifetime3: "Suporte premium dedicado",
        featureLifetime4: "Melhor custo-benefício",
        btnLifetime: "Comprar vitalício",
        guaranteeLifetime: "🔒 Pagamento único · Acesso vitalício garantido",
        stat1: "13",
        statLabel1: "Idiomas disponíveis",
        stat2: "6",
        statLabel2: "Temas visuais",
        stat3: "100%",
        statLabel3: "Dados locais",
        stat4: "24/7",
        statLabel4: "Sempre ativo",
        faqTag: "FAQ",
        faqTitle: "Perguntas <em>frequentes</em>",
        faqSubtitle: "Respostas às perguntas comuns.",
        faq1Q: "O teste gratuito requer cartão de crédito?",
        faq1A: "Sim, um cartão é necessário para o teste, mas você não será cobrado durante os primeiros 7 dias. Você pode cancelar a qualquer momento antes do fim do teste.",
        faq2Q: "Posso mudar de plano a qualquer momento?",
        faq2A: "Sim, você pode fazer upgrade ou downgrade a qualquer momento no seu portal do cliente. Sem taxas de mudança.",
        faq3Q: "O plano Vitalício realmente inclui todas as atualizações futuras?",
        faq3A: "Absolutamente. O plano Vitalício garante acesso a todas as atualizações e novos recursos para sempre, sem nunca pagar nada mais.",
        faq4Q: "Meus dados estão seguros?",
        faq4A: "Todos os seus dados ficam armazenados localmente no seu dispositivo. Não coletamos dados pessoais e não usamos rastreamento ou telemetria.",
        faq5Q: "Como entro em contato com o suporte?",
        faq5A: "Entre em contato diretamente por email em seymoon.cell@gmail.com. Assinantes premium recebem resposta prioritária.",
        roadmapTitle: "Em breve",
        roadmapSoon: "EM BREVE (Março 2026)",
        roadmapSoonTitle: "Lançamento na Chrome Web Store",
        roadmapSoon1: "Download oficial do Google",
        roadmapSoon2: "Instalação com 1 clique",
        roadmapSoon3: "Atualizações automáticas",
        roadmapSoon4: "Sem mais Mediafire",
        roadmapDev: "EM DESENVOLVIMENTO (T2 2026)",
        roadmapDevTitle: "Aplicação Desktop",
        roadmapDev1: "Windows, macOS, Linux",
        roadmapDev2: "Funciona com TODOS os jogos",
        roadmapDev3: "Suporte a jogos cliente (não navegador)",
        roadmapDev4: "Interface standalone",
        roadmapNewsletter: "📧 Fique informado",
        roadmapNewsletterDesc: "Inscreva-se na newsletter para anúncios de lançamento",
        footerDocs: "Documentação",
        footerPrivacy: "Privacidade",
        footerLegal: "Termos de Uso",
        footerSupport: "Suporte",
        footerContact: "Contato",
        footerCopyright: "© 2026 Reborn Assistant. Todos os direitos reservados.<br>Desenvolvido por Seymoon"
    }
};

// JE CONTINUE AVEC LES 8 DERNIÈRES LANGUES (JA, KO, ZH, RU, PL, NL, TL + système)...
