export default {
  hero: {
    description: "Browser automation extension with advanced macros. Automate your repetitive actions, shortcuts and sequences to optimize your productivity.",
    ctaPrimary:   "Get Started",
    ctaSecondary: "Learn More",
    trust1: "Free version available",
    trust2: "No commitment",
    trust3: "100% secure payment",
    trust4: "Automatic updates",
  },
  features: {
    tag:         "Skills & Abilities",
    titleBefore: "Everything you ",
    titleEm:     "need",
    subtitle:    "Discover the exceptional capabilities of Reborn Assistant.",
    card1: { badge: "Active",  title: "Complete Automation",      description: "Key macros, automatic sequences and configurable actions for complete automation." },
    card2: { badge: "Passive", title: "Maximum Security",         description: "Your data stays local. No tracking, no telemetry." },
    card3: { badge: "Active",  title: "Customizable Macros",      description: "3 configurable macros with automatic triggers and keyboard shortcuts." },
    card4: { badge: "Passive", title: "Customizable Interface",   description: "Choose from 6 themes and adapt the interface to your needs." },
    card5: { badge: "Passive", title: "Multi-Language",           description: "Available in 14 languages. Worldwide support with localized interfaces." },
    card6: { badge: "Free",    title: "Free Version",             description: "Try it free with basic features included." },
  },
  security: {
    tag:         "Security",
    titleBefore: "",
    titleEm:     "Professional-grade",
    titleAfter:  " security",
    description: "Reborn Assistant uses the same security standards as major streaming platforms. Your credentials are protected by <strong style='color:var(--gold);'>JWT encryption</strong>, your payments secured via <strong style='color:var(--gold);'>Stripe</strong>, and your data stays <strong style='color:var(--gold);'>100% local</strong>. No tracking, no data resale.",
    card1Title: "JWT Encryption",
    card1Text:  "Bank-grade secure authentication",
    card2Title: "Stripe Payment",
    card2Text:  "Processor used by Amazon & Google",
    card3Title: "Zero Tracking",
    card3Text:  "Your data never leaves your device",
    card4Text:  "Secure Google Cloud infrastructure",
  },
  pricing: {
    tag:         "Choose your Class",
    titleBefore: "Choose your ",
    titleEm:     "rank",
    subtitle:    "Choose the plan that suits you. No commitment.",
    voyageur: {
      rank: "Rank I · Traveler", plan: "Free", period: "forever",
      feat1: "Heal macro", feat2: "6 visual themes", feat3: "14 languages available", feat4: "Floating interface",
      btn: "Get Started", guarantee: "🔒 Free forever",
    },
    aventurier: {
      rank: "Rank II · Adventurer", plan: "Monthly", period: "per month",
      feat1: "All Premium features", feat2: "Priority support", feat3: "Free updates",
      btn: "Try Free", guarantee: "🎁 7 days free · No credit card required",
      download: "⬇ Download extension",
    },
    champion: {
      badge: "⭐ Popular -17%",
      rank: "Rank III · Champion", plan: "Yearly", period: "per year · only 2.50€/month",
      feat1: "All Premium features", feat2: "Priority support", feat3: "Free updates",
      btn: "Try Free", guarantee: "🎁 7 days free · No credit card required",
      download: "⬇ Download extension",
    },
    legende: {
      badge: "⚡ Limited Offer",
      rank: "Rank IV · Legend", plan: "Lifetime", period: "one-time payment · nothing ever again",
      feat1: "Lifetime access", feat2: "All future updates", feat3: "Dedicated premium support", feat4: "Best value for money",
      btn: "Buy Now", guarantee: "🔒 One-time payment · Lifetime access guaranteed",
      download: "⬇ Download extension",
    },
  },
  stats: {
    label1: "Languages available", label2: "Visual themes", label3: "Local data", label4: "Extension active",
  },
  trust: {
    badge1: "SSL secure payment", badge2: "Instant access", badge3: "100% private data", badge4: "Responsive support",
  },
  store: {
    status: "Under review",
    title:  "🟢 Available in preview · Google Chrome Web Store",
  },
  faq: {
    titleBefore: "Frequently Asked ",
    titleEm:     "Questions",
    subtitle:    "Everything you need to know before getting started.",
    q1: "Does the free trial require a credit card?",
    a1: "No credit card required. The first 7 days are completely free, with no commitment. Simply create your account to get started immediately.",
    q2: "Can I change plans at any time?",
    a2: "Yes, you can upgrade or downgrade at any time from your customer portal. No change fees.",
    q3: "Does the Lifetime plan really include all future updates?",
    a3: "Absolutely. The Lifetime plan guarantees access to all future updates and new features, without ever paying anything more.",
    q4: "Is my data safe?",
    a4: "All your data is stored locally on your device. We collect no personal data and use no tracking or telemetry.",
    q5: "How do I contact support?",
    a5: "Contact us directly by email at seymoon.cell@gmail.com. Premium subscribers receive priority responses.",
  },
  footer: {
    privacy:   "Privacy",
    terms:     "Terms of Use",
    copyright: "© 2026 Reborn Assistant. All rights reserved.<br>Developed by Seymoon",
  },
};
