export default {
  hero: {
    description: "Extensión de automatización del navegador con macros avanzadas. Automatiza tus acciones repetitivas, atajos y secuencias para optimizar tu productividad.",
    ctaPrimary: "Comenzar ahora",
    ctaSecondary: "Saber más",
    trust1: "Versión gratuita disponible",
    trust2: "Sin compromiso",
    trust3: "Pago 100% seguro",
    trust4: "Actualizaciones automáticas",
  },
  features: {
    tag: "Habilidades & Aptitudes",
    titleBefore: "Todo lo que ",
    titleEm: "necesitas",
    subtitle: "Descubre las capacidades excepcionales de Reborn Assistant.",
    card1: { badge: "Activo",   title: "Automatización Completa",    description: "Macros de teclas, secuencias automáticas y acciones configurables para una automatización completa." },
    card2: { badge: "Pasivo",   title: "Seguridad Máxima",           description: "Tus datos permanecen locales. Sin seguimiento, sin telemetría." },
    card3: { badge: "Activo",   title: "Macros Personalizables",     description: "3 macros configurables con activadores automáticos y atajos de teclado." },
    card4: { badge: "Pasivo",   title: "Interfaz Personalizable",    description: "Elige entre 6 temas y adapta la interfaz a tus necesidades." },
    card5: { badge: "Pasivo",   title: "Multi-Idioma",               description: "Disponible en 14 idiomas. Soporte mundial con interfaces localizadas." },
    card6: { badge: "Gratuito", title: "Versión Gratuita",           description: "Prueba gratis con las funciones básicas incluidas." },
  },
  security: {
    tag: "Seguridad",
    titleBefore: "Seguridad de nivel ",
    titleEm: "profesional",
    titleAfter: "",
    description: "Reborn Assistant utiliza los mismos estándares de seguridad que las plataformas de streaming mundiales. Tus credenciales están protegidas por <strong style='color:var(--gold);'>cifrado JWT</strong>, tus pagos asegurados mediante <strong style='color:var(--gold);'>Stripe</strong>, y tus datos permanecen <strong style='color:var(--gold);'>100% locales</strong>. Sin seguimiento, sin reventa de datos.",
    card1Title: "Cifrado JWT",
    card1Text:  "Autenticación segura de nivel bancario",
    card2Title: "Pago con Stripe",
    card2Text:  "Procesador utilizado por Amazon y Google",
    card3Title: "Cero Seguimiento",
    card3Text:  "Tus datos nunca salen de tu dispositivo",
    card4Text:  "Infraestructura segura de Google Cloud",
  },
  pricing: {
    tag:         "Elige tu Clase",
    titleBefore: "Elige tu ",
    titleEm:     "rango",
    subtitle:    "Elige la fórmula que más te convenga. Sin compromiso.",
    voyageur: {
      rank: "Rango I · Viajero", plan: "Gratuito", period: "para siempre",
      feat1: "Macro de curación", feat2: "6 temas visuales", feat3: "14 idiomas disponibles", feat4: "Interfaz flotante",
      btn: "Comenzar", download: "Añadir a Chrome", guarantee: "🔒 Gratis para siempre",
    },
    aventurier: {
      rank: "Rango II · Aventurero", plan: "Mensual", period: "por mes",
      feat1: "Todas las funciones Premium", feat2: "Soporte prioritario", feat3: "Actualizaciones gratuitas",
      btn: "Probar Gratis", guarantee: "🎁 7 días gratis · Sin tarjeta bancaria",
      download: "Añadir a Chrome",
    },
    champion: {
      badge: "⭐ Popular -17%",
      rank: "Rango III · Campeón", plan: "Anual", period: "por año · 2,50€/mes",
      feat1: "Todas las funciones Premium", feat2: "Soporte prioritario", feat3: "Actualizaciones gratuitas",
      btn: "Probar Gratis", guarantee: "🎁 7 días gratis · Sin tarjeta bancaria",
      download: "Añadir a Chrome",
    },
    legende: {
      badge: "⚡ Oferta Limitada",
      rank: "Rango IV · Leyenda", plan: "De por Vida", period: "pago único · nunca más",
      feat1: "Acceso de por vida", feat2: "Todas las actualizaciones futuras", feat3: "Soporte premium dedicado", feat4: "Mejor relación calidad-precio",
      btn: "Comprar", guarantee: "🔒 Pago único · Acceso garantizado de por vida",
      download: "Añadir a Chrome",
    },
  },
  stats: {
    label1: "Idiomas disponibles", label2: "Temas visuales", label3: "Datos locales", label4: "Extensión activa",
  },
  trust: {
    badge1: "Pago seguro SSL", badge2: "Acceso instantáneo", badge3: "Datos 100% privados", badge4: "Soporte reactivo",
  },
  store: {
    status: "Extensión oficial",
    title:  "Disponible en el Chrome Web Store",
    install: "Instalar",
    available: "Disponible gratis · Extensión oficial verificada por Google",
  },
  faq: {
    titleBefore: "Preguntas ",
    titleEm:     "frecuentes",
    subtitle:    "Todo lo que necesitas saber antes de empezar.",
    q1: "¿La prueba gratuita requiere tarjeta bancaria?",
    a1: "No, no se requiere ninguna tarjeta bancaria. Los primeros 7 días son completamente gratuitos, sin compromiso. Solo crea tu cuenta para comenzar de inmediato.",
    q2: "¿Puedo cambiar de plan en cualquier momento?",
    a2: "Sí, puedes pasar a un plan superior o inferior en cualquier momento desde tu cuenta. Sin cargos por cambio.",
    q3: "¿El plan De por Vida incluye realmente todas las actualizaciones futuras?",
    a3: "Absolutamente. El plan De por Vida te garantiza acceso a todas las actualizaciones y nuevas funciones futuras, sin pagar nada más.",
    q4: "¿Mis datos están seguros?",
    a4: "Todos tus datos se almacenan localmente en tu dispositivo. No recopilamos datos personales ni usamos seguimiento o telemetría.",
    q5: "¿Cómo contactar con el soporte?",
    a5: "Contáctanos directamente por correo electrónico en seymoon.cell@gmail.com. Los suscriptores premium reciben respuesta prioritaria.",
  },
  footer: {
    privacy:   "Privacidad",
    terms:     "Condiciones de Uso",
    copyright: "© 2026 Reborn Assistant. Todos los derechos reservados.<br>Desarrollado por Seymoon",
  },

  // ── Navegación compartida docs ────────────────────────────────────
  docsNav: {
    backToDocs:      "← Volver a la documentación",
    mainSite:        "⌂ Sitio principal",
    backToMainSite:  "← Volver al sitio principal",
    footer:          "© 2026 Reborn Assistant — Desarrollado por Seymoon · Todos los derechos reservados",
  },

  // ── docs/index.html ───────────────────────────────────────────────
  docsHome: {
    version:              "VERSIÓN 1.2 · DOCUMENTACIÓN COMPLETA",
    userGuide:            "Guía de usuario",
    support:              "Soporte",
    legal:                "Información legal",
    quickstartTitle:      "Inicio Rápido",
    quickstartDesc:       "Instalación, configuración inicial y primeros pasos con Reborn Assistant.",
    featuresTitle:        "Funcionalidades",
    featuresDesc:         "Detalle completo de las funciones gratuitas y Premium con tabla comparativa.",
    premiumTitle:         "Guía Premium",
    premiumDesc:          "Secuencias automáticas, macros personalizables y macro periódica.",
    interfaceTitle:       "Interfaz & Personalización",
    interfaceDesc:        "Temas visuales, idiomas y opciones de personalización.",
    troubleshootingTitle: "Solución de problemas",
    troubleshootingDesc:  "Soluciones a problemas comunes, preguntas frecuentes y optimización del rendimiento.",
    legalTitle:           "Legal & Privacidad",
    legalDesc:            "Aviso legal, menciones legales, términos de licencia, política de privacidad y registro de cambios.",
    footer:               "© 2026 Reborn Assistant — Desarrollado por Seymoon · Todos los derechos reservados",
  },

  // ── docs/features.html ────────────────────────────────────────────
  docFeatures: {
    h1:        "⚡ Funcionalidades",
    subtitle:  "Descubre todo lo que Reborn Assistant puede hacer por ti",
    h2Free:    "Funcionalidades GRATUITAS",
    freeBadge: "GRATIS",
    c1Title: "Acción automática de tipo 1",
    c1Desc:  "Activa automáticamente tu acción de tipo 1 (HP) según un temporizador configurable.",
    c1li1:   "Temporizador de acción configurable",
    c1li2:   "Funciona en segundo plano",
    c2Title: "Temas visuales",
    c2Desc:  "Personaliza la apariencia de la interfaz con 6 temas diferentes.",
    c2li1:   "MMO Gold (por defecto)",
    c2li2:   "Dark Mode & White Mode",
    c3Title: "Multi-idioma",
    c3Desc:  "Interfaz disponible en 14 idiomas para una experiencia internacional.",
    c3li3:   "Cambio instantáneo",
    h2Premium: "Funcionalidades PREMIUM 💎",
    p1Title: "Macro activador 1 automático",
    p1Desc:  "Activación automática de tu acción de tipo 1 (HP) según un temporizador configurable.",
    p1li1:   "Temporizador activador 1 configurable",
    p1li2:   "Tecla de acceso rápido configurable",
    p1li3:   "Funciona en segundo plano",
    p2Title: "Macro activador 2 automático",
    p2Desc:  "Uso automático de tus acciones de tipo 2 según un temporizador configurable.",
    p2li1:   "Temporizador activador 2 configurable",
    p2li2:   "Tecla de acceso rápido configurable",
    p2li3:   "Funciona en segundo plano",
    p3Title: "Atajos de teclado",
    p3Desc:  "Controla Reborn Assistant al vuelo con atajos globales personalizables.",
    p3li1:   "CTRL+A: Iniciar el bot",
    p3li2:   "CTRL+O: Detener el bot",
    p4Title: "Rotación de secuencias",
    p4Desc:  "Sistema automático de mantenimiento de secuencias con una secuencia predefinida.",
    p4li1:   "Secuencia: F2 → 1-9 → 0 → F1",
    p4li2:   "Intervalo configurable (minutos)",
    p4li3:   "Retraso entre teclas ajustable",
    p5Title: "Macros Personalizables",
    p5Desc:  "Crea hasta 3 macros con tus propias secuencias de teclas.",
    p5li1:   "3 macros independientes",
    p5li2:   "Secuencias personalizadas",
    p5li3:   "Intervalos de repetición ajustables",
    p6Title: "Macro periódica",
    p6Desc:  "Llamada y almacenamiento automático de tu macro periódica cada 15 segundos.",
    p6li1:   "Llamada automática de la macro periódica",
    p6li2:   "Auto-almacenamiento tras la llamada",
    p6li3:   "Intervalo fijo de 15 segundos",
    tableH2:      "Tabla comparativa",
    tableFeature: "Funcionalidad",
    tableFree:    "Gratis",
    row1:  "Acción automática de tipo 1 (HP)",
    row2:  "Temas visuales (6)",
    row3:  "Multi-idioma (14)",
    row4:  "Macro activador 1 automático",
    row5:  "Macro activador 2 automático",
    row6:  "Atajos de teclado (CTRL+A / CTRL+O)",
    row7:  "Rotación de secuencias automática",
    row8:  "Macros personalizables (3x)",
    row9:  "Macro periódica automática",
    learnMore: "→ Más información sobre las funciones Premium",
  },

  // ── docs/quickstart.html ──────────────────────────────────────────
  docQuickstart: {
    h1:       "🚀 Inicio Rápido",
    subtitle: "Instala y configura Reborn Assistant en pocos minutos",
    reqH2:    "Requisitos",
    req1:     "<strong>Navegador compatible:</strong> Google Chrome, Microsoft Edge, Brave o cualquier navegador basado en Chromium",
    req2:     "<strong>Cuenta de Google:</strong> Requerida solo para la autenticación Premium (opcional para la versión gratuita)",
    req3:     "<strong>Sitio compatible:</strong> Compatible con sitios web estándar",
    installH2:  "Instalación",
    step1Title: "Visitar el Chrome Web Store",
    step1p:     "Ve a la página de Reborn Assistant en el <a href='https://chromewebstore.google.com/detail/reborn-assistant-premium/ammakeedbimichmpipeaacgajcblnnme' target='_blank' style='color:var(--gold);text-decoration:none;' onmouseover='this.style.textDecoration=\"underline\"' onmouseout='this.style.textDecoration=\"none\"'>Chrome Web Store</a> y haz clic en <strong>«Añadir a Chrome»</strong>.",
    step1tip:   "💡 Compatible con Google Chrome, Microsoft Edge, Brave y cualquier navegador basado en Chromium.",
    step2Title: "Confirmar la instalación",
    step2p:     "Haz clic en <strong>«Añadir extensión»</strong> en la ventana de confirmación. La extensión se instala automáticamente.",
    step3Title: "Fijar la extensión",
    step3p:     "Haz clic en el ícono puzzle 🧩 en la barra de herramientas de tu navegador, luego fija Reborn Assistant para un acceso rápido.",
    step4Title: "Inicio de sesión (opcional para Premium)",
    step4p:     "• Haz clic en el ícono de Reborn en la barra de herramientas<br>• Para Premium: Inicia sesión con tu cuenta de Google<br>• Para Gratis: Úsalo directamente sin inicio de sesión",
    alertTitle: "✅ ¡Instalación exitosa!",
    alertText:  "El ícono de Reborn se vuelve verde cuando la extensión está activa. Ahora puedes configurar tus funciones.",
    configH2:   "Configuración inicial",
    freeH3:     "Versión GRATUITA",
    freeTitle:  "<strong>Funciones disponibles sin inicio de sesión:</strong>",
    freeText:   "• Acción automática de tipo 1 (solo HP)<br>• 6 temas visuales<br>• Soporte de 14 idiomas",
    freeStepTitle: "Configuración de la acción automática de tipo 1",
    freeStepText:  "1. Abre el panel de Reborn (clic en el ícono)<br>2. Ajusta el temporizador de la acción HP (por defecto: 2s)<br>3. La acción se activa automáticamente<br>4. No se requiere inicio de sesión",
    premiumH3:       "Versión PREMIUM 💎",
    premiumFeatTitle:"<strong>Funciones adicionales (requiere inicio de sesión con Google):</strong>",
    premiumFeatText: "• Macro activador 1 automático (temporizador configurable + atajo)<br>• Macro activador 2 automático (temporizador configurable + atajo)<br>• Atajos de teclado (CTRL+A / CTRL+O)<br>• Rotación automática de secuencias (F2 → 1-9 → 0 → F1)<br>• 3 macros personalizables con secuencias de teclas<br>• Sistema de macro periódica automático (llamada + almacenamiento cada 15s)",
    premConfigTitle: "Configuración Premium",
    premConfigSeq:   "<strong>Secuencias automáticas:</strong><br>• Activa «Rotación de Secuencias» en el panel<br>• Configura el intervalo entre ciclos (por defecto: 5 min)<br>• Ajusta el retraso entre cada tecla (por defecto: 1s)",
    premConfigMacro: "<strong>Macros:</strong><br>• Activa Macro 1, 2 o 3<br>• Define la secuencia de teclas (ej: <code>1,2,3,4</code>)<br>• Configura el intervalo de repetición",
    premConfigPer:   "<strong>Macro periódica:</strong><br>• Activa el interruptor «Macro periódica»<br>• El sistema llama automáticamente a tu macro periódica cada 15s<br>• Almacenamiento automático tras la llamada",
    warnTitle: "⚠️ Nota importante",
    warnText:  "Las funciones Premium (Macros activadores 1 y 2, Secuencias automáticas, Macro periódica automática, 3 macros configurables) requieren una licencia Premium válida y un inicio de sesión de Google. Sin licencia, solo está disponible la macro básica.",
    shortcutsH2:   "Atajos de teclado",
    shortcutsText: "<code>CTRL + A</code>: Iniciar el bot<br><code>CTRL + O</code>: Detener el bot",
    nextH2: "Próximos pasos",
    link1:  "Descubre todas las funcionalidades",
    link2:  "Guía completa Premium",
    link3:  "Soluciones a problemas comunes",
  },

  // ── docs/interface.html ───────────────────────────────────────────
  docInterface: {
    h1:       "🎨 Interfaz & Personalización",
    subtitle: "Personaliza Reborn Assistant según tus preferencias",
    themesH2:    "Temas visuales",
    themesDesc:  "Reborn Assistant ofrece 6 temas para personalizar la apariencia de la interfaz:",
    changeThemeH3:   "Cambiar de tema",
    changeThemeText: "1. Abre el panel de Reborn<br>2. Haz clic en la pestaña \"⚙️ CONFIGURACIÓN\"<br>3. Selecciona tu tema en el menú desplegable<br>4. El cambio es instantáneo",
    langsH2:    "Idiomas disponibles",
    langsDesc:  "Interfaz disponible en 14 idiomas:",
    changeLangH3:   "Cambiar de idioma",
    changeLangText: "1. Abre el panel de Reborn<br>2. Haz clic en \"⚙️ CONFIGURACIÓN\"<br>3. Selecciona tu idioma en el menú desplegable<br>4. Toda la interfaz se traduce al instante",
    shortcutsH2:   "Atajos de teclado",
    shortcutsDesc: "Reborn Assistant incluye atajos globales para un control rápido:",
    systemH3: "Atajos del sistema",
    sysSC1:   "<code>CTRL + A</code>: Iniciar el bot",
    sysSC2:   "<code>CTRL + O</code>: Detener el bot",
    customH3:   "Atajos personalizables",
    customDesc: "Puedes configurar las teclas para:",
    customLi1:  "Acciones de tipo 1 y 2",
    customLi2:  "Macros (secuencias de teclas)",
    customLi3:  "Macro periódica",
    displayH2:    "Opciones de visualización",
    panelPosH3:   "Posición del panel",
    panelPosDesc: "El panel de Reborn es arrastrable:",
    panelLi1: "Haz clic en el encabezado del panel",
    panelLi2: "Mantén el botón presionado y arrastra",
    panelLi3: "Suelta en el lugar deseado",
    panelLi4: "La posición se guarda automáticamente",
    opacityH3:   "Opacidad del panel",
    opacityDesc: "Ajusta la transparencia para no interferir con tu navegación mientras controlas tus estadísticas.",
    logH3:   "Registro de actividad",
    logDesc: "El registro muestra en tiempo real todas las acciones realizadas:",
    logLi1:  "Activación/desactivación de sistemas",
    logLi2:  "Uso de pociones",
    logLi3:  "Ejecución de macros y secuencias",
    logLi4:  "Llamadas a la macro periódica",
    logLi5:  "Posibles errores",
    saveH2:    "Guardado de parámetros",
    saveDesc:  "Todas tus configuraciones se guardan automáticamente de forma local:",
    saveLi1:   "Tema seleccionado",
    saveLi2:   "Idioma de la interfaz",
    saveLi3:   "Umbrales de activación",
    saveLi4:   "Teclas asignadas",
    saveLi5:   "Configuración de macros",
    saveLi6:   "Posición del panel",
    savePersist: "Persisten entre sesiones, incluso después de cerrar el navegador.",
  },

  // ── docs/premium.html ─────────────────────────────────────────────
  docPremium: {
    h1:       "💎 Guía Premium",
    subtitle: "Domina todas las funciones avanzadas de Reborn Assistant",
    rotH2:    "🛡️ Rotación de secuencias automática",
    rotDesc:  "El sistema de rotación mantiene automáticamente todas tus secuencias activas presionando una secuencia predefinida de teclas a intervalos regulares.",
    rotSeqH3:   "Secuencia de teclas",
    rotSeqText: "La rotación siempre sigue este orden fijo:",
    rotConfigH3:   "Configuración",
    rotIntName:    "Intervalo entre ciclos",
    rotIntDesc:    "Tiempo de espera antes de reiniciar toda la secuencia. Por defecto: 5 minutos. Ajusta según la duración de tus secuencias más cortas.",
    rotDelName:    "Retraso entre teclas",
    rotDelDesc:    "Tiempo de espera entre cada tecla de la secuencia. Por defecto: 1 segundo. Ajusta según la velocidad del servicio (animaciones, cooldowns...).",
    rotExTitle:    "💡 Ejemplo de uso",
    rotExScenario: "<strong>Escenario:</strong> Tus secuencias duran 5 minutos y tienes 8 secuencias en las teclas 1-8.",
    rotExConfig:   "<strong>Configuración:</strong>",
    rotExLi1:      "Intervalo: 5 minutos",
    rotExLi2:      "Retraso: 1 segundo",
    rotExLi3:      "El bot presionará F2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, F1 cada 5 minutos",
    rotExLi4:      "13 teclas en total con 1 segundo entre cada una = ~13 segundos por ciclo",
    macH2:    "⚙️ Macros Personalizables",
    macDesc:  "Crea hasta 3 macros independientes con tus propias secuencias de teclas. Perfecto para automatizar tareas repetitivas, combos recurrentes o rotaciones de habilidades.",
    macHowH3:   "Funcionamiento",
    macHowText: "Cada macro ejecuta una secuencia de teclas a intervalos regulares, de forma independiente a los demás sistemas.",
    macConfigH3:  "Configuración",
    macSeqName:   "Secuencia de teclas",
    macSeqDesc:   "Define las teclas a presionar en orden, separadas por comas. Ejemplo: 1,2,3,4 o q,w,e,r,f",
    macRepName:   "Intervalo de repetición",
    macRepDesc:   "Tiempo de espera antes de repetir la secuencia. Configura según tus necesidades (segundos o minutos).",
    macDelName:   "Retraso entre teclas",
    macDelDesc:   "Tiempo de espera entre cada tecla de la secuencia (generalmente 0,5 a 2 segundos).",
    macExTitle:   "💡 Ejemplos de uso",
    mac1Title:    "<strong>Macro 1 – Automatización repetitiva:</strong>",
    mac1Li1:      "Secuencia: 1,2,3,space",
    mac1Li2:      "Intervalo: 10 segundos",
    mac1Li3:      "Uso: Rotación de ataques básicos en bucle",
    mac2Title:    "<strong>Macro 2 – Combo de habilidades:</strong>",
    mac2Li1:      "Secuencia: q,w,e,r",
    mac2Li2:      "Intervalo: 30 segundos",
    mac2Li3:      "Uso: Rotación DPS óptima",
    mac3Title:    "<strong>Macro 3 – Soporte automático:</strong>",
    mac3Li1:      "Secuencia: f,g,h",
    mac3Li2:      "Intervalo: 15 segundos",
    mac3Li3:      "Uso: Secuencias de grupo o acciones periódicas",
    perH2:    "🐉 Macro periódica",
    perDesc:  "Este sistema ejecuta automáticamente una acción periódica cada 15 segundos. Ideal para tareas repetitivas que deben activarse regularmente.",
    perHowH3:   "Funcionamiento",
    perHowText: "El sistema ejecuta automáticamente esta secuencia cada 15 segundos:",
    perLi1:     "Llama a la macro periódica (tecla configurable, por defecto §)",
    perLi2:     "Espera 500ms",
    perLi3:     "Almacena la macro periódica automáticamente",
    perConfigH3:  "Configuración",
    perCallName:  "Tecla de llamada",
    perCallDesc:  "La tecla que activa tu macro periódica. Por defecto: §. Modifícala según tu configuración.",
    perIntName:   "Intervalo (fijo)",
    perIntDesc:   "El sistema siempre usa un intervalo fijo de 15 segundos. No configurable.",
    perExTitle:   "💡 Caso de uso",
    perExText:    "En algunos servicios, la macro periódica debe llamarse regularmente para recoger objetos, proporcionar secuencias temporales o ganar experiencia. Este sistema automatiza completamente este proceso.",
    perImpH3:     "⚠️ Importante",
    perImpLi1:    "Verifica que la tecla configurada corresponde a tu tecla de invocación",
    perImpLi2:    "La macro periódica se almacena automáticamente después de cada llamada",
    perImpLi3:    "Funciona en paralelo con los demás sistemas (secuencias, macros, acciones)",
    optH2:   "Consejos de optimización",
    combH3:  "🎯 Combinación de sistemas",
    combDesc:"Todas las funciones Premium funcionan simultáneamente. Puedes:",
    combLi1: "Activar secuencias automáticas + 3 macros + macro periódica al mismo tiempo",
    combLi2: "Las acciones activadoras 1 &amp; 2 siempre funcionan en paralelo",
    combLi3: "Cada sistema tiene su propio temporizador independiente",
    perfH3:  "⚡ Rendimiento",
    perfLi1: "Cuantos más sistemas actives, más recursos consume la extensión",
    perfLi2: "Ajusta los intervalos para evitar acciones demasiado frecuentes",
    perfLi3: "Monitorea el registro de actividad para verificar el correcto funcionamiento",
    secH3:   "🔑 Seguridad",
    secLi1:  "Tu licencia Premium se verifica en tiempo real",
    secLi2:  "Si se pierde la conexión, las funciones Premium se desactivan",
    secLi3:  "Vuelve a iniciar sesión para reactivar todas las funciones",
  },

  // ── docs/troubleshooting.html ─────────────────────────────────────
  docTroubleshooting: {
    h1:       "🔧 Solución de problemas",
    subtitle: "Soluciones a problemas comunes y preguntas frecuentes",
    installH2: "Problemas de instalación",
    faq1Q: "❌ La extensión no aparece en la barra de herramientas",
    faq1A: "<strong>Soluciones:</strong><br>1. Verifica que la extensión esté instalada desde el <strong>Chrome Web Store</strong><br>2. Fija la extensión: haz clic en el ícono puzzle 🧩 en la barra de herramientas y fija Reborn Assistant<br>3. Reinicia tu navegador<br>4. Si el problema persiste, desinstala y reinstala la extensión desde el Chrome Web Store",
    connH2: "Problemas de conexión",
    faq2Q: "❌ \"Conexión fallida\" o \"Licencia inválida\"",
    faq2A: "<strong>Posibles causas:</strong><br>• Mala conexión a internet<br>• Servidores de Google Cloud temporalmente no disponibles<br>• Licencia expirada o revocada<br><br><strong>Soluciones:</strong><br>1. Verifica tu conexión a internet<br>2. Cierra sesión y vuelve a iniciarla con Google<br>3. Verifica el estado de tu licencia en tu portal Stripe<br>4. Contacta con el soporte si el problema persiste",
    faq3Q: "❌ El panel muestra \"FREE\" aunque tengo Premium",
    faq3A: "1. Cierra sesión de tu cuenta de Google<br>2. Cierra completamente el navegador<br>3. Vuelve a abrir e inicia sesión<br>4. Si el problema persiste, verifica que estás conectado con la cuenta de Google correcta (la usada para la compra)",
    funcH2: "Problemas de funcionamiento",
    faq4Q:     "❌ Las acciones de tipo 1/2 no se activan",
    faq4Alert: "<strong>⚠️ IMPORTANTE</strong><br>Las acciones de tipo 1 y 2 son funciones <strong>EXCLUSIVAMENTE PREMIUM</strong>. Solo la acción automática de tipo 1 (HP) está disponible en la versión gratuita.",
    faq4Prem:  "<strong>Si tienes Premium:</strong><br>1. ¿Está iniciado el bot? <code>CTRL+A</code><br>2. ¿Están activados los interruptores activadores? (indicador verde «ON»)<br>3. ¿Son correctas las teclas configuradas?",
    faq5Q:     "❌ Las secuencias / macros / macro periódica / atajos no funcionan",
    faq5Alert: "<strong>⚠️ IMPORTANTE</strong><br>Los atajos de teclado, secuencias, macros y macro periódica son funciones <strong>EXCLUSIVAMENTE PREMIUM</strong>. En la versión gratuita, solo está disponible la acción automática de tipo 1 (HP).",
    faq5Prem:  "<strong>Si tienes Premium:</strong><br>1. Verifica que tu licencia Premium esté activa (ícono 💎 en el panel)<br>2. ¿Están activados los interruptores correspondientes?<br>3. Verifica los intervalos y retrasos configurados",
    faq6Q: "❌ El bot se detiene solo",
    faq6A: "<strong>Posibles causas:</strong><br>• Pérdida de conexión a Google Cloud<br>• Detección de DevTools<br>• La URL de la página cambió<br><br><strong>Soluciones:</strong><br>1. Reinicia el bot con <code>CTRL+A</code> (Premium) o desde el panel<br>2. Recarga la página afectada<br>3. Verifica tu conexión a internet<br>4. No abras DevTools si estás en Premium",
    optH2: "Optimización & Rendimiento",
    faq7Q: "💡 El bot consume demasiados recursos",
    faq7A: "<strong>Recomendaciones:</strong><br>• Aumenta los intervalos de macros y secuencias (menos acciones = menos CPU)<br>• Desactiva los sistemas que no necesitas<br>• Cierra las pestañas innecesarias<br>• Usa un navegador optimizado (Brave, Edge son más ligeros que Chrome)",
    faq8Q: "💡 ¿Cómo optimizar la configuración?",
    faq8A: "<strong>Configuración recomendada:</strong><br>• <strong>Intervalo secuencias:</strong> 5-25 minutos (según duración de tus secuencias)<br>• <strong>Retraso entre teclas:</strong> 1-2 segundos (evita errores)<br>• <strong>Macros:</strong> Intervalos de 10-30s según el uso",
    genH2:  "Preguntas Frecuentes",
    faq9Q:  "❓ ¿Puedo usar Reborn en varios navegadores?",
    faq9A:  "Sí, pero debes instalar la extensión en cada navegador. Tu licencia Premium funciona en todos tus dispositivos mientras inicies sesión con la misma cuenta de Google (máx. 1 conexión simultánea).",
    faq10Q: "❓ ¿Se guardan mis datos?",
    faq10A: "Todas tus configuraciones (teclas, macros, tema, idioma) se guardan <strong>localmente</strong> en el navegador. Persisten entre sesiones. Sin embargo, si desinstala la extensión, perderás estos datos.",
    faq11Q: "❓ ¿Puede Reborn provocar un baneo?",
    faq11A: "El uso de herramientas de automatización puede violar los Términos de Servicio de algunos servicios. <strong>Eres el único responsable</strong> de cómo usas Reborn. Consulta los términos de uso del servicio antes de usar esta herramienta.",
    faq12Q: "❓ ¿Cómo cancelar mi suscripción Premium?",
    faq12A: "Puedes cancelar en cualquier momento desde tu portal de gestión de Stripe (enlace recibido por correo electrónico tras el pago). La cancelación tiene efecto al final de tu período actual. Sin cargos por cancelación.",
    faq13Q: "❓ ¿Qué pasa con el plan De por Vida si el servicio cierra?",
    faq13A: "El plan De por Vida garantiza el acceso mientras el servicio esté activo. Una vez instalada, la extensión funciona localmente; solo la verificación de licencia requiere conexión a internet.",
    supportH2:    "¿Necesitas más ayuda?",
    supportTitle: "📧 Soporte",
    supportText:  "Si tu problema persiste, contacta con el soporte directamente por correo electrónico. Incluye en tu mensaje:<br><br>• Una descripción detallada del problema<br>• Los pasos que ya has intentado<br>• Capturas de pantalla si son relevantes<br>• Tu navegador y sistema operativo",
  },

  // ── docs/privacy.html ─────────────────────────────────────────────
  docPrivacy: {
    h1:       "⚖️ Legal & Privacidad",
    subtitle: "Aviso legal, menciones legales, términos de licencia y política de privacidad",
    navLegal:  "⚖️ Información Legal",
    navLicence:"© Licencia",
    navPrivacy:"🔒 Privacidad",
    disclaimerH2:  "⚠️ Aviso Legal",
    disclaimerBox: "<strong>⚠️ Aviso importante:</strong> Reborn Assistant es una herramienta de automatización. Su uso puede violar los Términos de Servicio de ciertos servicios en línea. El uso de esta herramienta es completamente bajo tu propio riesgo.",
    respH3:    "Responsabilidad del usuario",
    respIntro: "Al usar Reborn Assistant, reconoces y aceptas que:",
    respLi1:   "Eres el único responsable del uso que haces de este software",
    respLi2:   "Verificarás los términos de uso de cada servicio antes de usar esta herramienta",
    respLi3:   "El autor no puede ser considerado responsable de ningún baneo, restricción de cuenta, o acción legal resultante del uso de Reborn",
    respLi4:   "Usas este software conscientemente y bajo tu propio riesgo",
    respLi5:   "Esta herramienta no debe usarse de manera que perjudique la experiencia de otros usuarios",
    warrantH3:   "Sin garantía",
    warrantText: "El software se proporciona \"TAL CUAL\" sin garantía de ningún tipo. El autor no garantiza que el software funcione de manera ininterrumpida o sin errores, ni que sea compatible con todos los servicios o navegadores.",
    legalH2:    "📄 Menciones legales",
    copyrightH3:   "Derechos de autor & Propiedad intelectual",
    copyrightText: "<strong>© 2026 Reborn Assistant – Todos los derechos reservados</strong><br>Desarrollado por <strong>Seymoon</strong>",
    copyrightText2:"Este software y todos los materiales asociados son propiedad intelectual exclusiva de su autor. Cualquier reproducción, modificación, distribución o ingeniería inversa sin autorización escrita está estrictamente prohibida.",
    liabilityH3:   "Limitación de responsabilidad",
    liabilityIntro:"En ningún caso el autor será responsable de ninguna reclamación o daño derivado del uso o la imposibilidad de usar este software, incluyendo pero no limitado a:",
    liabilityLi1:  "Pérdida de datos o cuenta de usuario",
    liabilityLi2:  "Baneos o restricciones impuestos por editores de servicios",
    liabilityLi3:  "Daños a sistemas informáticos",
    liabilityLi4:  "Cualquier consecuencia legal derivada de un uso no conforme a los términos de servicio",
    dataH3:    "Datos personales",
    dataText:  "Reborn Assistant utiliza Firebase (Google Cloud) para la gestión de cuentas y licencias. Los datos recopilados se limitan a tu dirección de correo electrónico e identificador de cuenta, únicamente para fines de autenticación y verificación de licencia.",
    dataText2: "<strong>No se recopilan ni transmiten datos de actividad.</strong> Tus configuraciones permanecen almacenadas localmente en tu dispositivo.",
    jurisH3:   "Jurisdicción",
    jurisText: "Este acuerdo se rige por la ley aplicable en la jurisdicción de residencia del titular de los derechos de autor. Al instalar y usar este software, reconoces haber leído, comprendido y aceptado la totalidad de estas condiciones.",
    licenceH2:     "© Términos de licencia",
    licenceH3:     "Licencia de uso",
    licenceIntro:  "La compra de un plan de Reborn Assistant te otorga una licencia personal, no exclusiva y no transferible para usar el software.",
    licenceAllows: "<strong>Esta licencia te autoriza a:</strong>",
    licenceLi1:    "Usar el software para fines personales en tus propios dispositivos",
    licenceLi2:    "Beneficiarte de las actualizaciones incluidas en tu plan",
    licenceForbids:"<strong>Esta licencia no te autoriza a:</strong>",
    licenceLi3:    "Redistribuir, revender o compartir tu acceso",
    licenceLi4:    "Modificar, descompilar o realizar ingeniería inversa del software",
    licenceLi5:    "Usar el software con fines comerciales sin acuerdo escrito previo",
    licenceLi6:    "Transferir tu licencia a un tercero",
    terminationH3:   "Rescisión",
    terminationText: "La licencia puede rescindirse inmediatamente en caso de incumplimiento de estos términos. Para los planes de suscripción, puedes cancelar en cualquier momento desde tu portal de Stripe.",
    refundBox: "<strong>✅ Política de reembolso:</strong> Si no estás satisfecho en los 7 días siguientes a tu compra, contacta con nuestro soporte para un reembolso completo. Pasado este período, no se concederá ningún reembolso salvo casos excepcionales.",
    privacyH1:      "🔒 Política de Privacidad",
    privacySubtitle:"Cómo protegemos tus datos personales",
    privacyBox:     "<strong>✅ Privacidad total garantizada</strong><br>Reborn Assistant no recopila, transmite ni almacena ningún dato personal en servidores externos. Tu privacidad es nuestra prioridad absoluta.",
    collectH2:   "Recopilación de datos",
    collectText: "<strong>Reborn Assistant NO recopila NINGÚN dato personal.</strong>",
    collectText2:"Todas las preferencias y configuraciones se almacenan <strong>localmente en tu dispositivo</strong> mediante la API de almacenamiento local del navegador (<code>chrome.storage.local</code>). Sin transmisión a servidores externos.",
    localH2:    "Datos almacenados localmente",
    localIntro: "La siguiente información se guarda <strong>únicamente en tu dispositivo</strong>:",
    localLi1:   "<strong>Preferencias de idioma</strong>: Tu elección de idioma de interfaz",
    localLi2:   "<strong>Selección del tema visual</strong>: El tema elegido entre los 6 disponibles",
    localLi3:   "<strong>Atajos de teclado configurados</strong>: Las teclas asignadas para tus acciones",
    localLi4:   "<strong>Intervalos de temporizador personalizados</strong>: Los temporizadores configurados para tus macros",
    localLi5:   "<strong>Posición de la interfaz</strong>: La ubicación del panel de Reborn en tu pantalla",
    thirdH2:      "Servicios de terceros",
    thirdH3:      "Ningún servicio de seguimiento utilizado",
    thirdDesc:    "Reborn Assistant <strong>no utiliza ningún</strong> servicio externo como:",
    thirdLi1:     "❌ Servicios de análisis (Google Analytics, Mixpanel...)",
    thirdLi2:     "❌ Servicios de seguimiento (píxeles de seguimiento, cookies de terceros)",
    thirdLi3:     "❌ Servicios de publicidad",
    thirdLi4:     "❌ Servicios de telemetría",
    authH2:       "Autenticación y licencia",
    authH3:       "Firebase Authentication (versión Premium)",
    authText:     "Para los usuarios Premium, Reborn utiliza <strong>Firebase Authentication</strong> (Google Cloud) únicamente para verificar tu licencia y autenticar tu cuenta de Google.",
    authText2:    "<strong>Datos concernidos:</strong> tu dirección de correo electrónico de Google y tu identificador de Google Cloud (UID). Estos datos solo se usan para la verificación de licencia.",
    payH2:    "Pagos Seguros",
    payText:  "Los pagos Premium son procesados por <strong>Stripe</strong>. Tu información bancaria <strong>nunca</strong> pasa por nuestros servidores. No almacenamos <strong>ningún dato</strong> de tarjeta bancaria.",
    deleteH2:    "Eliminación de tus datos",
    deleteText1: "<strong>1. Desinstalar la extensión</strong><br>Al desinstalar Reborn Assistant, todos los datos locales se eliminan automáticamente.",
    deleteText2: "<strong>2. Restablecimiento manual</strong><br>Puedes restablecer la configuración desde la interfaz de Reborn en cualquier momento.",
    deleteText3: "<strong>3. Eliminación de cuenta (Premium)</strong><br>Para eliminar tu cuenta Premium y todos los datos asociados, contáctanos por correo electrónico.",
    contactH2:   "Contacto",
    contactText: "Para cualquier pregunta sobre información legal o política de privacidad:",
    changelogH2: "📋 Registro de cambios",
    v12H3:   "Versión 1.2 (Febrero 2026) · Actual",
    v12Li1:  "Soporte de 14 idiomas (añadido Turco 🇹🇷)",
    v12Li2:  "Rediseño visual del sitio web",
    v12Li3:  "Fusión de páginas legales en una sola página unificada",
    v12Li4:  "Traducción completa FR/EN del sitio",
    v11H3:   "Versión 1.1 (Febrero 2026)",
    v11Li1:  "Añadida macro periódica automática (15s + auto-almacenamiento)",
    v11Li2:  "Atajos de teclado CTRL+A / CTRL+O",
    v11Li3:  "Soporte de 14 idiomas (añadido Filipino + Turco)",
    v11Li4:  "Mejora de la estabilidad de la licencia Premium",
    v11Li5:  "Correcciones de errores en la rotación de secuencias",
    v10H3:   "Versión 1.0 (2025) · Inicial",
    v10Li1:  "Lanzamiento de Reborn Assistant",
    v10Li2:  "Acciones automáticas de tipo 1 y 2",
    v10Li3:  "Rotación de secuencias automática (F2 → 1-9 → 0 → F1)",
    v10Li4:  "3 macros personalizables",
    v10Li5:  "6 temas visuales y 12 idiomas",
    v10Li6:  "Sistema de licencia Premium mediante Firebase",
    pageFooter:"© 2026 Reborn Assistant — Desarrollado por Seymoon · Todos los derechos reservados",
  },
};
