export default {
  hero: {
    description: "Extensión de Automatización del Navegador con Macros avanzadas. Automatiza tus acciones repetitivas, atajos y secuencias para optimizar tu productividad.",
    ctaPrimary:   "Comenzar ahora",
    ctaSecondary: "Saber más",
    trust1: "Versión gratuita disponible",
    trust2: "Sin compromiso",
    trust3: "Pago 100% seguro",
    trust4: "Actualizaciones automáticas",
  },
  features: {
    tag:         "Habilidades & Aptitudes",
    titleBefore: "Todo lo que ",
    titleEm:     "necesitas",
    subtitle:    "Descubre las capacidades excepcionales de Reborn Assistant.",
    card1: { badge: "Activo", title: "Automatización Completa",    description: "Macros de teclas, secuencias automáticas y acciones configurables para una automatización completa." },
    card2: { badge: "Pasivo", title: "Seguridad Máxima",           description: "Tus datos permanecen locales. Sin rastreo, sin telemetría." },
    card3: { badge: "Activo", title: "Macros Personalizables",     description: "3 Macros configurables con activadores automáticos y atajos de teclado." },
    card4: { badge: "Pasivo", title: "Interfaz Personalizable",    description: "Elige entre 6 temas y adapta la interfaz a tus necesidades." },
    card5: { badge: "Pasivo", title: "Multi-Idioma",               description: "Disponible en 14 idiomas. Soporte mundial con interfaces localizadas." },
    card6: { badge: "Gratis", title: "Versión Gratuita",           description: "Pruébalo gratis con las funciones básicas incluidas." },
  },
  security: {
    tag:         "Seguridad",
    titleBefore: "Seguridad de nivel ",
    titleEm:     "profesional",
    titleAfter:  "",
    description: "Reborn Assistant utiliza los mismos estándares de seguridad que las plataformas de streaming mundiales. Tus credenciales están protegidas por <strong style='color:var(--gold);'>cifrado JWT</strong>, tus pagos asegurados a través de <strong style='color:var(--gold);'>Stripe</strong>, y tus datos permanecen <strong style='color:var(--gold);'>100% locales</strong>. Sin rastreo, sin reventa de datos.",
    card1Title: "Cifrado JWT",
    card1Text:  "Autenticación segura de nivel bancario",
    card2Title: "Pago con Stripe",
    card2Text:  "Procesador utilizado por Amazon y Google",
    card3Title: "Cero Rastreo",
    card3Text:  "Tus datos nunca abandonan tu dispositivo",
    card4Text:  "Infraestructura segura de Google Cloud",
  },
  pricing: {
    tag:         "Elige tu Clase",
    titleBefore: "Elige tu ",
    titleEm:     "rango",
    subtitle:    "Elige el plan que más te convenga. Sin compromiso.",
    voyageur: {
      rank: "Rango I · Viajero", plan: "Gratuito", period: "para siempre",
      feat1: "Macro de curación", feat2: "6 temas visuales", feat3: "14 idiomas disponibles", feat4: "Interfaz flotante",
      btn: "Comenzar", guarantee: "🔒 Gratis para siempre",
    },
    aventurier: {
      rank: "Rango II · Aventurero", plan: "Mensual", period: "por mes",
      feat1: "Todas las funciones Premium", feat2: "Soporte prioritario", feat3: "Actualizaciones gratuitas",
      btn: "Probar Gratis", guarantee: "🎁 7 días gratis · Sin tarjeta bancaria",
      download: "⬇ Descargar la extensión",
    },
    champion: {
      badge: "⭐ Popular -17%",
      rank: "Rango III · Campeón", plan: "Anual", period: "por año · solo 2,50€/mes",
      feat1: "Todas las funciones Premium", feat2: "Soporte prioritario", feat3: "Actualizaciones gratuitas",
      btn: "Probar Gratis", guarantee: "🎁 7 días gratis · Sin tarjeta bancaria",
      download: "⬇ Descargar la extensión",
    },
    legende: {
      badge: "⚡ Oferta Limitada",
      rank: "Rango IV · Leyenda", plan: "Vitalicio", period: "pago único · nunca más nada",
      feat1: "Acceso de por vida", feat2: "Todas las actualizaciones futuras", feat3: "Soporte premium dedicado", feat4: "Mejor relación calidad-precio",
      btn: "Comprar", guarantee: "🔒 Pago único · Acceso garantizado de por vida",
      download: "⬇ Descargar la extensión",
    },
  },
  stats: {
    label1: "Idiomas disponibles", label2: "Temas visuales", label3: "Datos locales", label4: "Extensión activa",
  },
  trust: {
    badge1: "Pago seguro SSL", badge2: "Acceso instantáneo", badge3: "Datos 100% privados", badge4: "Soporte reactivo",
  },
  store: {
    status: "En proceso de validación",
    title:  "🟢 Disponible en vista previa · Google Chrome Web Store",
  },
  faq: {
    titleBefore: "Preguntas ",
    titleEm:     "frecuentes",
    subtitle:    "Todo lo que necesitas saber antes de empezar.",
    q1: "¿La prueba gratuita requiere tarjeta bancaria?",
    a1: "No, no se requiere tarjeta bancaria. Los primeros 7 días son completamente gratuitos, sin compromiso. Solo crea tu cuenta para empezar de inmediato.",
    q2: "¿Puedo cambiar de plan en cualquier momento?",
    a2: "Sí, puedes cambiar a un plan superior o inferior en cualquier momento desde tu área de cliente. Sin costes de cambio.",
    q3: "¿El plan Vitalicio incluye realmente todas las actualizaciones futuras?",
    a3: "Absolutamente. El plan Vitalicio te garantiza acceso a todas las actualizaciones y nuevas funciones futuras, sin pagar nada más nunca.",
    q4: "¿Están seguros mis datos?",
    a4: "Todos tus datos se almacenan localmente en tu dispositivo. No recopilamos datos personales ni usamos rastreo o telemetría.",
    q5: "¿Cómo contactar al soporte?",
    a5: "Contáctanos directamente por correo electrónico a seymoon.cell@gmail.com. Los suscriptores Premium reciben respuesta prioritaria.",
  },
  footer: {
    privacy:   "Privacidad",
    terms:     "Términos de Uso",
    copyright: "© 2026 Reborn Assistant. Todos los derechos reservados.<br>Desarrollado por Seymoon",
  },
};
