export default {
  hero: {
    description: "Extension d'automatisation pour navigateur avec macros avancées. Automatisez vos actions répétitives, raccourcis et séquences pour optimiser votre productivité.",
    ctaPrimary: "Commencer maintenant",
    ctaSecondary: "En savoir plus",
    trust1: "Version gratuite disponible",
    trust2: "Sans engagement",
    trust3: "Paiement 100% sécurisé",
    trust4: "Mises à jour automatiques",
  },
  features: {
    tag: "Compétences & Aptitudes",
    titleBefore: "Tout ce dont vous ",
    titleEm: "avez besoin",
    subtitle: "Découvrez les capacités exceptionnelles de Reborn Assistant.",
    card1: { badge: "Actif",  title: "Automatisation Complète",    description: "Macros de touches, séquences automatiques et actions configurables pour une automatisation complète." },
    card2: { badge: "Passif", title: "Sécurité Maximale",          description: "Vos données restent locales. Aucun tracking, aucune télémétrie." },
    card3: { badge: "Actif",  title: "Macros Personnalisables",    description: "3 macros configurables avec déclencheurs automatiques et raccourcis clavier." },
    card4: { badge: "Passif", title: "Interface Personnalisable",  description: "Choisissez parmi 6 thèmes et adaptez l'interface à vos besoins." },
    card5: { badge: "Passif", title: "Multi-Langues",              description: "Disponible en 14 langues. Support mondial avec interfaces localisées." },
    card6: { badge: "Gratuit",title: "Version Gratuite",           description: "Testez gratuitement avec les fonctionnalités de base incluses." },
  },
  security: {
    tag: "Sécurité",
    titleBefore: "Niveau de sécurité ",
    titleEm: "professionnel",
    titleAfter: "",
    description: "Reborn Assistant utilise les mêmes standards de sécurité que les plateformes de streaming mondiales. Vos identifiants sont protégés par <strong style='color:var(--gold);'>chiffrement JWT</strong>, vos paiements sécurisés via <strong style='color:var(--gold);'>Stripe</strong>, et vos données restent <strong style='color:var(--gold);'>100% locales</strong>. Aucun tracking, aucune revente de données.",
    card1Title: "Chiffrement JWT",
    card1Text:  "Authentification sécurisée de niveau bancaire",
    card2Title: "Paiement Stripe",
    card2Text:  "Processeur utilisé par Amazon & Google",
    card3Title: "Zéro Tracking",
    card3Text:  "Vos données ne quittent jamais votre appareil",
    card4Text:  "Infrastructure Google Cloud sécurisée",
  },
  pricing: {
    tag:         "Choisissez votre Classe",
    titleBefore: "Choisissez votre ",
    titleEm:     "rang",
    subtitle:    "Choisissez la formule qui vous convient. Sans engagement.",
    voyageur: {
      rank: "Rang I · Voyageur", plan: "Gratuit", period: "à jamais",
      feat1: "Macro soin", feat2: "6 thèmes visuels", feat3: "14 langues disponibles", feat4: "Interface flottante",
      btn: "Commencer", guarantee: "🔒 Gratuit pour toujours",
    },
    aventurier: {
      rank: "Rang II · Aventurier", plan: "Mensuel", period: "par mois",
      feat1: "Toutes les fonctionnalités Premium", feat2: "Support prioritaire", feat3: "Mises à jour gratuites",
      btn: "Essayer Gratuitement", guarantee: "🎁 7 jours gratuits · Sans carte bancaire",
      download: "⬇ Télécharger l'extension",
    },
    champion: {
      badge: "⭐ Populaire -17%",
      rank: "Rang III · Champion", plan: "Annuel", period: "par an · soit 2,50€/mois",
      feat1: "Toutes les fonctionnalités Premium", feat2: "Support prioritaire", feat3: "Mises à jour gratuites",
      btn: "Essayer Gratuitement", guarantee: "🎁 7 jours gratuits · Sans carte bancaire",
      download: "⬇ Télécharger l'extension",
    },
    legende: {
      badge: "⚡ Offre Limitée",
      rank: "Rang IV · Légende", plan: "À Vie", period: "paiement unique · plus jamais rien",
      feat1: "Accès à vie", feat2: "Toutes les mises à jour futures", feat3: "Support premium dédié", feat4: "Meilleur rapport qualité-prix",
      btn: "Acheter", guarantee: "🔒 Paiement unique · Accès garanti à vie",
      download: "⬇ Télécharger l'extension",
    },
  },
  stats: {
    label1: "Langues disponibles", label2: "Thèmes visuels", label3: "Données locales", label4: "Extension active",
  },
  trust: {
    badge1: "Paiement sécurisé SSL", badge2: "Accès instantané", badge3: "Données 100% privées", badge4: "Support réactif",
  },
  store: {
    status: "En cours de validation",
    title:  "🟢 Disponible en prévisualisation · Google Chrome Web Store",
  },
  faq: {
    titleBefore: "Questions ",
    titleEm:     "fréquentes",
    subtitle:    "Tout ce que vous devez savoir avant de commencer.",
    q1: "L'essai gratuit nécessite-t-il une carte bancaire ?",
    a1: "Non, aucune carte bancaire n'est requise. Les 7 premiers jours sont entièrement gratuits, sans engagement. Vous n'avez qu'à créer votre compte pour commencer immédiatement.",
    q2: "Puis-je changer de plan à tout moment ?",
    a2: "Oui, vous pouvez passer à un plan supérieur ou inférieur à tout moment depuis votre espace client. Aucun frais de changement.",
    q3: "Le plan À Vie inclut-il vraiment toutes les futures mises à jour ?",
    a3: "Absolument. Le plan À Vie vous garantit l'accès à toutes les mises à jour et nouvelles fonctionnalités futures, sans jamais débourser quoi que ce soit de plus.",
    q4: "Mes données sont-elles en sécurité ?",
    a4: "Toutes vos données restent stockées localement sur votre appareil. Nous ne collectons aucune donnée personnelle et n'utilisons aucun tracking ou télémétrie.",
    q5: "Comment contacter le support ?",
    a5: "Contactez-nous directement par email à seymoon.cell@gmail.com. Les abonnés premium bénéficient d'une réponse prioritaire.",
  },
  footer: {
    privacy:   "Confidentialité",
    terms:     "Conditions d'Utilisation",
    copyright: "© 2026 Reborn Assistant. Tous droits réservés.<br>Développé par Seymoon",
  },
};
